services:
  game:
    image: cogame-factorio-game:latest
    platform: linux/amd64
    build: {context: ., dockerfile: Dockerfile, network: host}
  player:
    image: cogame-factorio-player:latest
    platform: linux/amd64
    build: {context: ., dockerfile: Dockerfile, network: host}
